apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k3s-vault-cluster-role-binding
subjects:
- namespace: vault
  kind: ServiceAccount
  name: k3s-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k3s-vault-role